### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-logstore_usage#3]
Code review found a few parts that could hurt performance. They are executed for each event (read: very often) and should therefore be improved. 

1. https://github.com/learnweb/moodle-logstore_usage/blob/af73744e6995f28bc67965dd350b5ec2d8bc9d85/classes/log/store.php#L70

`preg_match` is fine if there is a pattern, but for fixed strings direct comparisons are better. I'd go with something along the lines of
`substr_compare($str, $test, strlen($str)-strlen($test), strlen($test)) === 0;` 
instead. ([docs](https://www.php.net/substr_compare))

2. https://github.com/learnweb/moodle-logstore_usage/blob/af73744e6995f28bc67965dd350b5ec2d8bc9d85/classes/log/store.php#L82

Exploding and traversing a string array takes its time. This is not so relevant as long as we are logging for just one course, but we should be doing this the right way from the start. Consider creating an [application cache](https://docs.moodle.org/dev/Cache_API#Creating_a_definition) for this value. The cache could be purged whenever the setting is changed.

**Comment by tobiasreischmann** [comment]
Also by c9a47a33d6f2c9380ab051a0965ba6fd49de9da1
